import type { CardDefinition } from "../progression/progression.types";

export const RARITY_WEIGHTS = {
  common: 65,
  rare: 27,
  legendary: 8,
} as const;

export const RARITY_COLORS = {
  common: "#9aa0a6",
  rare: "#5aa9e6",
  legendary: "#e8b73a",
} as const;

export const RARITY_TEXT_COLORS = {
  common: "#50545a",
  rare: "#1f638f",
  legendary: "#73520a",
} as const;

export const CARD_DEFINITIONS: readonly CardDefinition[] = [
  {
    id: "common_sharpened_edge",
    kind: "common",
    rarity: "rare",
    name: "Sharpened Edge",
    description: "Fresh-honed steel lets every formation strike deeper.",
    maxStacks: 2,
    effect: { attackDamageMultiplier: 1.12 },
  },
  {
    id: "common_drilled_ranks",
    kind: "common",
    rarity: "rare",
    name: "Drilled Ranks",
    description: "Relentless drills turn hesitation into a faster cadence.",
    maxStacks: 2,
    effect: { attackIntervalMultiplier: 0.88 },
  },
  {
    id: "common_hardened_flesh",
    kind: "common",
    rarity: "common",
    name: "Hardened Flesh",
    description: "Old scars become armor against the coming dark.",
    maxStacks: 3,
    effect: { maxHpBonus: 25 },
  },
  {
    id: "common_wider_watch",
    kind: "common",
    rarity: "common",
    name: "Wider Watch",
    description: "Far-seeing sentries sound the alarm before shadows close.",
    maxStacks: 2,
    effect: { threatSenseRadiusBonus: 60 },
  },
  {
    id: "common_unbroken_will",
    kind: "common",
    rarity: "rare",
    name: "Unbroken Will",
    description: "Even bloodied ranks hold when lesser hearts would break.",
    maxStacks: 2,
    effect: { breakHpRatioDelta: -0.1 },
  },
  {
    id: "common_swift_muster",
    kind: "common",
    rarity: "common",
    name: "Swift Muster",
    description: "Signal horns bring every warrior swiftly to the line.",
    maxStacks: 2,
    effect: { moveSpeedMultiplier: 1.15 },
  },
  {
    id: "house_a_emberguard",
    kind: "house",
    rarity: "rare",
    houseId: "house_a",
    name: "Emberguard",
    description: "Ashvale tempers its blades in the fire beneath the hall.",
    maxStacks: 1,
    effect: { attackDamageMultiplier: 1.15 },
  },
  {
    id: "house_a_pyre_rites",
    kind: "house",
    rarity: "rare",
    houseId: "house_a",
    name: "Pyre Rites",
    description: "Warm embers knit wounds while the war drums rest.",
    maxStacks: 2,
    effect: { interWaveHealBonus: 25 },
  },
  {
    id: "house_b_tidewall",
    kind: "house",
    rarity: "rare",
    houseId: "house_b",
    name: "Tidewall",
    description: "Thornhold stands like a seawall against the black tide.",
    maxStacks: 2,
    effect: { maxHpBonus: 40 },
  },
  {
    id: "house_b_deep_horns",
    kind: "house",
    rarity: "rare",
    houseId: "house_b",
    name: "Deep Horns",
    description: "Low horns carry the hall's alarm across the battlefield.",
    maxStacks: 2,
    effect: { hallDefenseRadiusBonus: 90 },
  },
  {
    id: "house_c_greenward",
    kind: "house",
    rarity: "rare",
    houseId: "house_c",
    name: "Greenward",
    description: "Greymoor's living ward restores flesh and hardens bone.",
    maxStacks: 2,
    effect: { interWaveHealBonus: 20, maxHpBonus: 15 },
  },
  {
    id: "house_c_thicket_pact",
    kind: "house",
    rarity: "rare",
    houseId: "house_c",
    name: "Thicket Pact",
    description: "Each fallen invader pays tribute to the patient roots.",
    maxStacks: 2,
    effect: { tributePerKillBonus: 2 },
  },
  {
    id: "divine_wider_wrath",
    kind: "divine",
    rarity: "rare",
    name: "Wider Wrath",
    description: "Your judgment rolls outward like thunder over the field.",
    maxStacks: 2,
    effect: { miracleRadiusMultiplier: 1.25 },
  },
  {
    id: "divine_open_channel",
    kind: "divine",
    rarity: "rare",
    name: "Open Channel",
    description: "The veil thins and divine power returns in a brighter stream.",
    maxStacks: 2,
    effect: { divineRegenMultiplier: 1.3 },
  },
  {
    id: "hero_ashvale_ember_duelist",
    kind: "hero",
    rarity: "rare",
    houseId: "house_a",
    heroId: "hero_ashvale",
    name: "Ember Duelist",
    description: "Sera turns every opening into a decisive strike.",
    maxStacks: 2,
    effect: { heroDamageMultiplier: 1.2 },
  },
  {
    id: "hero_ashvale_rising_flame",
    kind: "hero",
    rarity: "rare",
    houseId: "house_a",
    heroId: "hero_ashvale",
    name: "Rising Flame",
    description: "Sera returns sooner whenever the ember line breaks.",
    maxStacks: 2,
    effect: { heroRespawnTicksMultiplier: 0.8 },
  },
  {
    id: "hero_thornhold_iron_body",
    kind: "hero",
    rarity: "rare",
    houseId: "house_b",
    heroId: "hero_thornhold",
    name: "Iron Body",
    description: "Bren's oath hardens him beyond mortal endurance.",
    maxStacks: 2,
    effect: { heroMaxHpMultiplier: 1.25 },
  },
  {
    id: "hero_thornhold_oath_strike",
    kind: "hero",
    rarity: "rare",
    houseId: "house_b",
    heroId: "hero_thornhold",
    name: "Oath Strike",
    description: "Bren answers every blow with measured force.",
    maxStacks: 2,
    effect: { heroDamageMultiplier: 1.15 },
  },
  {
    id: "hero_greymoor_wider_boughs",
    kind: "hero",
    rarity: "rare",
    houseId: "house_c",
    heroId: "hero_greymoor",
    name: "Wider Boughs",
    description: "Ivy's living song reaches farther across the field.",
    maxStacks: 2,
    effect: { heroAuraRadiusBonus: 35 },
  },
  {
    id: "hero_greymoor_green_mercy",
    kind: "hero",
    rarity: "rare",
    houseId: "house_c",
    heroId: "hero_greymoor",
    name: "Green Mercy",
    description: "Ivy's kills mend nearby allies beneath her living ward.",
    maxStacks: 2,
    effect: { heroOnKillHeal: 12 },
  },
  {
    id: "legend_last_bastion",
    kind: "common",
    rarity: "legendary",
    name: "Last Bastion",
    description:
      "While any hall is below 25% HP, every agent deals 30% more damage.",
    maxStacks: 1,
    effect: {},
  },
  {
    id: "legend_martyrs_ember",
    kind: "common",
    rarity: "legendary",
    name: "Martyr's Ember",
    description: "Each agent death grants 4 divine power.",
    maxStacks: 1,
    effect: { divinePowerPerAgentDeath: 4 },
  },
  {
    id: "legend_ironblood",
    kind: "common",
    rarity: "legendary",
    name: "Ironblood",
    description: "Agents below 40% HP take 35% less damage.",
    maxStacks: 1,
    effect: {},
  },
  {
    id: "legend_ash_crown",
    kind: "house",
    rarity: "legendary",
    houseId: "house_a",
    name: "Ash Crown",
    description: "Ashvale agents ignore the break rule entirely.",
    maxStacks: 1,
    effect: { ignoreBreak: true },
  },
  {
    id: "legend_deeproot",
    kind: "house",
    rarity: "legendary",
    houseId: "house_c",
    name: "Deeproot",
    description: "Gain 6 tribute per kill and towers cost 40% less.",
    maxStacks: 1,
    effect: { tributePerKillBonus: 6, towerCostMultiplier: 0.6 },
  },
  {
    id: "legend_twin_souls",
    kind: "hero",
    rarity: "legendary",
    name: "Twin Souls",
    description:
      "Heroes respawn in half the time and return with 150% of their normal max HP.",
    maxStacks: 1,
    effect: {
      heroRespawnTicksMultiplier: 0.5,
      heroRespawnHpMultiplier: 1.5,
    },
  },
  {
    id: "divine_grant_chains",
    kind: "divine",
    rarity: "rare",
    name: "Chains of Dusk",
    description: "Unlock the Chains of Dusk active divine skill.",
    maxStacks: 1,
    effect: { grantsSkill: "chains_of_dusk" },
  },
  {
    id: "divine_grant_sanctuary",
    kind: "divine",
    rarity: "rare",
    name: "Sanctuary",
    description: "Unlock the Sanctuary active divine skill.",
    maxStacks: 1,
    effect: { grantsSkill: "sanctuary" },
  },
  {
    id: "divine_grant_meteor",
    kind: "divine",
    rarity: "legendary",
    name: "Meteor Fall",
    description: "Unlock the Meteor Fall active divine skill.",
    maxStacks: 1,
    effect: { grantsSkill: "meteor_fall" },
  },
  {
    id: "divine_grant_resurgence",
    kind: "divine",
    rarity: "legendary",
    name: "Resurgence",
    description: "Unlock the Resurgence active divine skill.",
    maxStacks: 1,
    effect: { grantsSkill: "resurgence" },
  },
];
