import type { CardDefinition } from "../progression/progression.types";

export const CARD_DEFINITIONS: readonly CardDefinition[] = [
  {
    id: "common_sharpened_edge",
    kind: "common",
    name: "Sharpened Edge",
    description: "Fresh-honed steel lets every formation strike deeper.",
    maxStacks: 2,
    effect: { attackDamageMultiplier: 1.12 },
  },
  {
    id: "common_drilled_ranks",
    kind: "common",
    name: "Drilled Ranks",
    description: "Relentless drills turn hesitation into a faster cadence.",
    maxStacks: 2,
    effect: { attackIntervalMultiplier: 0.88 },
  },
  {
    id: "common_hardened_flesh",
    kind: "common",
    name: "Hardened Flesh",
    description: "Old scars become armor against the coming dark.",
    maxStacks: 3,
    effect: { maxHpBonus: 25 },
  },
  {
    id: "common_wider_watch",
    kind: "common",
    name: "Wider Watch",
    description: "Far-seeing sentries sound the alarm before shadows close.",
    maxStacks: 2,
    effect: { threatSenseRadiusBonus: 60 },
  },
  {
    id: "common_unbroken_will",
    kind: "common",
    name: "Unbroken Will",
    description: "Even bloodied ranks hold when lesser hearts would break.",
    maxStacks: 2,
    effect: { breakHpRatioDelta: -0.1 },
  },
  {
    id: "common_swift_muster",
    kind: "common",
    name: "Swift Muster",
    description: "Signal horns bring every warrior swiftly to the line.",
    maxStacks: 2,
    effect: { moveSpeedMultiplier: 1.15 },
  },
  {
    id: "house_a_emberguard",
    kind: "house",
    houseId: "house_a",
    name: "Emberguard",
    description: "Ashvale tempers its blades in the fire beneath the hall.",
    maxStacks: 1,
    effect: { attackDamageMultiplier: 1.15 },
  },
  {
    id: "house_a_pyre_rites",
    kind: "house",
    houseId: "house_a",
    name: "Pyre Rites",
    description: "Warm embers knit wounds while the war drums rest.",
    maxStacks: 2,
    effect: { interWaveHealBonus: 25 },
  },
  {
    id: "house_b_tidewall",
    kind: "house",
    houseId: "house_b",
    name: "Tidewall",
    description: "Thornhold stands like a seawall against the black tide.",
    maxStacks: 2,
    effect: { maxHpBonus: 40 },
  },
  {
    id: "house_b_deep_horns",
    kind: "house",
    houseId: "house_b",
    name: "Deep Horns",
    description: "Low horns carry the hall's alarm across the battlefield.",
    maxStacks: 2,
    effect: { hallDefenseRadiusBonus: 90 },
  },
  {
    id: "house_c_greenward",
    kind: "house",
    houseId: "house_c",
    name: "Greenward",
    description: "Greymoor's living ward restores flesh and hardens bone.",
    maxStacks: 2,
    effect: { interWaveHealBonus: 20, maxHpBonus: 15 },
  },
  {
    id: "house_c_thicket_pact",
    kind: "house",
    houseId: "house_c",
    name: "Thicket Pact",
    description: "Each fallen invader pays tribute to the patient roots.",
    maxStacks: 2,
    effect: { tributePerKillBonus: 2 },
  },
  {
    id: "divine_wider_wrath",
    kind: "divine",
    name: "Wider Wrath",
    description: "Your judgment rolls outward like thunder over the field.",
    maxStacks: 2,
    effect: { miracleRadiusMultiplier: 1.25 },
  },
  {
    id: "divine_open_channel",
    kind: "divine",
    name: "Open Channel",
    description: "The veil thins and divine power returns in a brighter stream.",
    maxStacks: 2,
    effect: { divineRegenMultiplier: 1.3 },
  },
  {
    id: "hero_ashvale_ember_duelist",
    kind: "hero",
    houseId: "house_a",
    heroId: "hero_ashvale",
    name: "Ember Duelist",
    description: "Sera turns every opening into a decisive strike.",
    maxStacks: 2,
    effect: { heroDamageMultiplier: 1.2 },
  },
  {
    id: "hero_ashvale_rising_flame",
    kind: "hero",
    houseId: "house_a",
    heroId: "hero_ashvale",
    name: "Rising Flame",
    description: "Sera returns sooner whenever the ember line breaks.",
    maxStacks: 2,
    effect: { heroRespawnTicksMultiplier: 0.8 },
  },
  {
    id: "hero_thornhold_iron_body",
    kind: "hero",
    houseId: "house_b",
    heroId: "hero_thornhold",
    name: "Iron Body",
    description: "Bren's oath hardens him beyond mortal endurance.",
    maxStacks: 2,
    effect: { heroMaxHpMultiplier: 1.25 },
  },
  {
    id: "hero_thornhold_oath_strike",
    kind: "hero",
    houseId: "house_b",
    heroId: "hero_thornhold",
    name: "Oath Strike",
    description: "Bren answers every blow with measured force.",
    maxStacks: 2,
    effect: { heroDamageMultiplier: 1.15 },
  },
  {
    id: "hero_greymoor_wider_boughs",
    kind: "hero",
    houseId: "house_c",
    heroId: "hero_greymoor",
    name: "Wider Boughs",
    description: "Ivy's living song reaches farther across the field.",
    maxStacks: 2,
    effect: { heroAuraRadiusBonus: 35 },
  },
  {
    id: "hero_greymoor_green_mercy",
    kind: "hero",
    houseId: "house_c",
    heroId: "hero_greymoor",
    name: "Green Mercy",
    description: "Ivy's kills mend nearby allies beneath her living ward.",
    maxStacks: 2,
    effect: { heroOnKillHeal: 12 },
  },
];
