import type { CardDefinition } from "../progression/progression.types";

export const RARITY_WEIGHTS = {
  common: 65,
  rare: 27,
  legendary: 8,
} as const;

export const CARD_DEFINITIONS: readonly CardDefinition[] = [
  {
    id: "common_sharpened_edge",
    kind: "common",
    rarity: "common",
    name: "Sharpened Edge",
    description: "Fresh-honed steel lets every formation strike deeper.",
    maxStacks: 3,
    effect: { attackDamageMultiplier: 1.12 },
  },
  {
    id: "common_drilled_ranks",
    kind: "common",
    rarity: "common",
    name: "Drilled Ranks",
    description: "Relentless drills turn hesitation into a faster cadence.",
    maxStacks: 3,
    effect: { attackIntervalMultiplier: 0.88 },
  },
  {
    id: "common_hardened_flesh",
    kind: "common",
    rarity: "common",
    name: "Hardened Flesh",
    description: "Old scars become armor against the coming dark.",
    maxStacks: 3,
    effect: { maxHpBonus: 25 },
  },
  {
    id: "common_wider_watch",
    kind: "common",
    rarity: "common",
    name: "Wider Watch",
    description: "Far-seeing sentries sound the alarm before shadows close.",
    maxStacks: 3,
    effect: { threatSenseRadiusBonus: 60 },
  },
  {
    id: "common_unbroken_will",
    kind: "common",
    rarity: "common",
    name: "Unbroken Will",
    description: "Even bloodied ranks hold when lesser hearts would break.",
    maxStacks: 3,
    effect: { breakHpRatioDelta: -0.1 },
  },
  {
    id: "common_swift_muster",
    kind: "common",
    rarity: "common",
    name: "Swift Muster",
    description: "Signal horns bring every warrior swiftly to the line.",
    maxStacks: 3,
    effect: { moveSpeedMultiplier: 1.15 },
  },
  {
    id: "common_stout_sinew",
    kind: "common",
    rarity: "common",
    name: "Stout Sinew",
    description: "Simple rationing gives each guard a little more staying power.",
    maxStacks: 3,
    effect: { maxHpBonus: 12 },
  },
  {
    id: "common_quickened_cadence",
    kind: "common",
    rarity: "common",
    name: "Quickened Cadence",
    description: "A steady drumbeat shaves a little time from each exchange.",
    maxStacks: 3,
    effect: { attackIntervalMultiplier: 0.96 },
  },
  {
    id: "common_tithe_mark",
    kind: "common",
    rarity: "common",
    name: "Tithe Mark",
    description: "Marked spoils send one extra tribute home with every kill.",
    maxStacks: 3,
    effect: { tributePerKillBonus: 1 },
  },
  {
    id: "common_bright_channel",
    kind: "common",
    rarity: "common",
    name: "Bright Channel",
    description: "A modest rite helps divine power return between crises.",
    maxStacks: 3,
    effect: { divineRegenMultiplier: 1.1 },
  },
  {
    id: "common_far_ward",
    kind: "common",
    rarity: "common",
    name: "Far Ward",
    description: "Small watchstones extend each hall's defensive reach.",
    maxStacks: 3,
    effect: { hallDefenseRadiusBonus: 30 },
  },
  {
    id: "common_warm_embers",
    kind: "common",
    rarity: "common",
    name: "Warm Embers",
    description: "Banked fires restore a little health between waves.",
    maxStacks: 3,
    effect: { interWaveHealBonus: 10 },
  },
  {
    id: "house_a_emberguard",
    kind: "house",
    rarity: "rare",
    houseId: "house_a",
    name: "Emberguard",
    description: "Ashvale tempers its blades in the fire beneath the hall.",
    maxStacks: 2,
    effect: { attackDamageMultiplier: 1.15 },
  },
  {
    id: "house_a_pyre_rites",
    kind: "house",
    rarity: "rare",
    houseId: "house_a",
    name: "Pyre Rites",
    description: "Warm embers knit wounds while the war drums rest.",
    maxStacks: 2,
    effect: { interWaveHealBonus: 25 },
  },
  {
    id: "house_b_tidewall",
    kind: "house",
    rarity: "rare",
    houseId: "house_b",
    name: "Tidewall",
    description: "Thornhold stands like a seawall against the black tide.",
    maxStacks: 2,
    effect: { maxHpBonus: 40 },
  },
  {
    id: "house_b_deep_horns",
    kind: "house",
    rarity: "rare",
    houseId: "house_b",
    name: "Deep Horns",
    description: "Low horns carry the hall's alarm across the battlefield.",
    maxStacks: 2,
    effect: { hallDefenseRadiusBonus: 90 },
  },
  {
    id: "house_c_greenward",
    kind: "house",
    rarity: "rare",
    houseId: "house_c",
    name: "Greenward",
    description: "Greymoor's living ward restores flesh and hardens bone.",
    maxStacks: 2,
    effect: { interWaveHealBonus: 20, maxHpBonus: 15 },
  },
  {
    id: "house_c_thicket_pact",
    kind: "house",
    rarity: "rare",
    houseId: "house_c",
    name: "Thicket Pact",
    description: "Each fallen invader pays tribute to the patient roots.",
    maxStacks: 2,
    effect: { tributePerKillBonus: 2 },
  },
  {
    id: "divine_wider_wrath",
    kind: "divine",
    rarity: "common",
    name: "Wider Wrath",
    description: "Your judgment rolls outward like thunder over the field.",
    maxStacks: 3,
    effect: { miracleRadiusMultiplier: 1.25 },
  },
  {
    id: "divine_open_channel",
    kind: "divine",
    rarity: "common",
    name: "Open Channel",
    description: "The veil thins and divine power returns in a brighter stream.",
    maxStacks: 3,
    effect: { divineRegenMultiplier: 1.3 },
  },
  {
    id: "hero_ashvale_ember_duelist",
    kind: "hero",
    rarity: "rare",
    houseId: "house_a",
    heroId: "hero_ashvale",
    name: "Ember Duelist",
    description: "Sera turns every opening into a decisive strike.",
    maxStacks: 2,
    effect: { heroDamageMultiplier: 1.2 },
  },
  {
    id: "hero_ashvale_rising_flame",
    kind: "hero",
    rarity: "rare",
    houseId: "house_a",
    heroId: "hero_ashvale",
    name: "Rising Flame",
    description: "Sera returns sooner whenever the ember line breaks.",
    maxStacks: 2,
    effect: { heroRespawnTicksMultiplier: 0.8 },
  },
  {
    id: "hero_thornhold_iron_body",
    kind: "hero",
    rarity: "rare",
    houseId: "house_b",
    heroId: "hero_thornhold",
    name: "Iron Body",
    description: "Bren's oath hardens him beyond mortal endurance.",
    maxStacks: 2,
    effect: { heroMaxHpMultiplier: 1.25 },
  },
  {
    id: "hero_thornhold_oath_strike",
    kind: "hero",
    rarity: "rare",
    houseId: "house_b",
    heroId: "hero_thornhold",
    name: "Oath Strike",
    description: "Bren answers every blow with measured force.",
    maxStacks: 2,
    effect: { heroDamageMultiplier: 1.15 },
  },
  {
    id: "hero_greymoor_wider_boughs",
    kind: "hero",
    rarity: "rare",
    houseId: "house_c",
    heroId: "hero_greymoor",
    name: "Wider Boughs",
    description: "Ivy's living song reaches farther across the field.",
    maxStacks: 2,
    effect: { heroAuraRadiusBonus: 35 },
  },
  {
    id: "hero_greymoor_green_mercy",
    kind: "hero",
    rarity: "rare",
    houseId: "house_c",
    heroId: "hero_greymoor",
    name: "Green Mercy",
    description: "Ivy's kills mend nearby allies beneath her living ward.",
    maxStacks: 2,
    effect: { heroOnKillHeal: 12 },
  },
  {
    id: "legend_last_bastion",
    kind: "common",
    rarity: "legendary",
    name: "Last Bastion",
    description:
      "While any hall is below 25% HP, every agent deals 30% more damage.",
    maxStacks: 1,
    effect: {},
  },
  {
    id: "legend_martyrs_ember",
    kind: "common",
    rarity: "legendary",
    name: "Martyr's Ember",
    description: "Each agent death grants 4 divine power.",
    maxStacks: 1,
    effect: { divinePowerPerAgentDeath: 4 },
  },
  {
    id: "legend_ironblood",
    kind: "common",
    rarity: "legendary",
    name: "Ironblood",
    description: "Agents below 40% HP take 35% less damage.",
    maxStacks: 1,
    effect: {},
  },
  {
    id: "legend_ash_crown",
    kind: "house",
    rarity: "legendary",
    houseId: "house_a",
    name: "Ash Crown",
    description:
      "Ashvale agents ignore the break rule entirely, but their attacks are slower.",
    maxStacks: 1,
    effect: { ignoreBreak: true, attackIntervalMultiplier: 1.18 },
  },
  {
    id: "legend_deeproot",
    kind: "house",
    rarity: "legendary",
    houseId: "house_c",
    name: "Deeproot",
    description:
      "Gain 6 tribute per kill and towers cost 40% less, but Greymoor moves slower.",
    maxStacks: 1,
    effect: {
      tributePerKillBonus: 6,
      towerCostMultiplier: 0.6,
      moveSpeedMultiplier: 0.85,
    },
  },
  {
    id: "legend_twin_souls",
    kind: "hero",
    rarity: "legendary",
    name: "Twin Souls",
    description:
      "Heroes respawn in half the time and return with 150% of their normal max HP, but regular agent durability falls.",
    maxStacks: 1,
    effect: {
      heroRespawnTicksMultiplier: 0.5,
      heroRespawnHpMultiplier: 1.5,
      maxHpMultiplier: 0.9,
    },
  },
  {
    id: "legend_zealots_bargain",
    kind: "common",
    rarity: "legendary",
    name: "Zealot's Bargain",
    description:
      "Agents deal 40% more damage, but they break much earlier under pressure.",
    maxStacks: 1,
    effect: { attackDamageMultiplier: 1.4, breakHpRatioDelta: 0.2 },
  },
  {
    id: "legend_hollow_crown",
    kind: "house",
    rarity: "legendary",
    houseId: "house_a",
    name: "Hollow Crown",
    description:
      "Ashvale doubles divine regeneration, but its owning house hero cannot respawn.",
    maxStacks: 1,
    effect: { divineRegenMultiplier: 2, disableHeroRespawn: true },
  },
  {
    id: "divine_grant_chains",
    kind: "divine",
    rarity: "rare",
    name: "Chains of Dusk",
    description: "Unlock the Chains of Dusk active divine skill.",
    maxStacks: 2,
    effect: { grantsSkill: "chains_of_dusk" },
  },
  {
    id: "divine_grant_sanctuary",
    kind: "divine",
    rarity: "rare",
    name: "Sanctuary",
    description: "Unlock the Sanctuary active divine skill.",
    maxStacks: 2,
    effect: { grantsSkill: "sanctuary" },
  },
  {
    id: "divine_grant_meteor",
    kind: "divine",
    rarity: "legendary",
    name: "Meteor Fall",
    description:
      "Unlock Meteor Fall: costs 55 divine power and damages friendly towers in the blast.",
    maxStacks: 1,
    effect: { grantsSkill: "meteor_fall" },
  },
  {
    id: "divine_grant_resurgence",
    kind: "divine",
    rarity: "legendary",
    name: "Resurgence",
    description:
      "Unlock Resurgence: costs 70 divine power with a 600 tick cooldown.",
    maxStacks: 1,
    effect: { grantsSkill: "resurgence" },
  },
];
